apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: flask-api
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/maxtacu/url-shortener.git
    targetRevision: HEAD
    path: infrastructure/k8s/flask-api
  destination:
    server: https://kubernetes.default.svc
    namespace: flask-shortener