openapi: 3.0.0
info:
  title: url-shortener
  version: '1.0'
  description: URL Shortener API service
  contact:
    name: Maxim Tacu
servers:
  - url: 'http://localhost:8080'
    description: HTTP
paths:
  '/{shorturl}':
    parameters:
      - schema:
          type: string
        name: shorturl
        in: path
        required: true
    get:
      summary: Redirect URL
      tags: []
      responses:
        '301':
          description: Moved Permanently
          headers:
            location:
              schema:
                type: string
                format: uri
              required: true
              description: Redirect location
            expires:
              schema:
                type: string
                format: date-time
              required: true
              description: Expiration date-time
        '404':
          description: Not Found
      operationId: api_server.apiroutes.redirect_shorturl
      description: Redirect to the long url which was added
  /api/add:
    parameters: []
    post:
      summary: Add URL
      operationId: api_server.apiroutes.create_shorturl
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Url'
      parameters:
        - schema:
            type: string
          in: query
          name: url
      description: Create your short link
  /api/stats:
    get:
      summary: All URL-shortener stats
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Url'
      operationId: api_server.apiroutes.get_stats_all
      description: Get stats on all existing links in database
    parameters: []
  '/api/stats/{shorturl}':
    parameters:
      - schema:
          type: string
        name: shorturl
        in: path
        required: true
    get:
      summary: Stats for a cpecific url
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Url'
      operationId: api_server.apiroutes.get_stats_shorturl
      description: Get specific link stats
components:
  schemas:
    Url:
      title: URL data
      type: object
      properties:
        redirect-url:
          type: string
          format: uri
          description: Shortened URL
        original-url:
          type: string
          format: uri
          description: Original URL
        expires:
          type: string
          description: Expiration datetime
        visits:
          type: integer
          description: Unique visits of the shortened url
      description: ''
