apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-api
  labels:
    app: flask-api
spec:
  selector:
    matchLabels:
      app: flask-api
  replicas: 1
  template:
    metadata:
      labels:
        app: flask-api
    spec:
      containers:
      - name: flask-api
        image: maxtacu/flask-urlshortener:0.0.1
        imagePullPolicy: Always
        env:
          # Use secret in real usage
        - name: DATABASE_URL
          value: "mysql+pymysql://root:password@mysql.mysql.svc.cluster.local:3306/flaskshortener"
        ports:
        - containerPort: 8080